#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

#yabai -m config external_bar               all:40:0       \
yabai -m config mouse_follows_focus        off            \
                window_zoom_persist        off            \
                window_placement           second_child   \
                window_shadow              float          \
                window_opacity             off             \
                window_opacity_duration    0.2            \
                active_window_opacity      1.0            \
                normal_window_opacity      0.9            \
                window_animation_duration  0.05            \
                window_animation_easing    ease_out_quint \
                insert_feedback_color      0xff9dd274     \
                split_ratio                0.50           \
                auto_balance               off            \
                mouse_modifier             fn             \
                mouse_action1              move           \
                mouse_action2              resize         \
                mouse_drop_action          swap           \
                                                          \
                top_padding                12              \
                bottom_padding             12              \
                left_padding               12              \
                right_padding              12              \
                window_gap                 12

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor|PureRef)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off

#Setting up the spaces
yabai -m space 1 --label 2D_Art
yabai -m space 2 --label Code
yabai -m space 3 --label 3D_Art
yabai -m space 4 --label Referances
yabai -m space 5 --label Web
yabai -m space 6 --label Media
yabai -m space 7 --label Social
yabai -m space 8 --label Games
yabai -m space 9 --label Productivity

#Move Certain App to certain spaces
yabai -m rule --add app="^Mail$" space=productivity
yabai -m rule --add app="^Brave Browser$" space=Web
yabai -m rule --add app="^Safari$" space=Web
yabai -m rule --add app="^Notes$" space=Productivity
yabai -m rule --add app="^CLIP STUDIO PAINT$" space=2D_Art manage=on
yabai -m rule --add app="^Blender$" space=3D_Art
yabai -m rule --add app="^Chromium$" space=Referances
yabai -m rule --add app="^Codium$" space=Code
yabai -m rule --add app="^Terminal$" space=Code

#Specific Space Configs
yabai -m config --space Referances layout bsp
yabai -m config --space 2D_Art layout float
yabai -m config --space Games layout float

# yabai -m rule --add app="^Mail$" space=mail
# yabai -m rule --add app="^Safari$" space=web
# yabai -m rule --add app="^Notes$" space=notes
# yabai -m rule --add app="^ida64$" space=re
# yabai -m rule --add app="^Transmission$" space=media
# yabai -m rule --add app="^Spotify$" space=media
# yabai -m rule --add app="^Discord$" space=social grid=1:1:0:0:1:1 manage=off
# yabai -m rule --add app="^Steam$" space=games manage=off
# yabai -m rule --add app="^(Calculator|System Preferences|Archive Utility)$" manage=off
# yabai -m rule --add app="^mpv$" manage=off border=off sticky=on layer=above opacity=1.0 grid=8:8:6:0:2:2
#
yabai -m config layout bsp


echo "yabai configuration loaded.."
